### ISSUE TITLE
Double.valueOf() produces wrong results

### ISSUE THREAD

**Issue by penberg** [jatovm/jato#1]
The following test case:

```
public class DoubleTest {
  public static void main(String[] args) {
    System.out.println(Double.valueOf(1.1));
  }
}
```

produces wrong results with Jato:

$ jato DoubleTest
1.1000000000000001

JamVM and OpenJDK do the right thing:

$ /usr/local/jamvm/bin/jamvm DoubleTest
1.1
$ java DoubleTest
1.1

It looks like the generated native code in Jato is wrong and Arhur and Tomek suspected we might be using the wrong SSE rounding mode. The problem is likely to be visible for Float.valueOf() and possibly other double and float operations.

**Comment by vegard** [comment]
http://folk.uio.no/vegardno/0001-debug-x86-Add-helper-functions-for-interfacing-with-.patch

This shows that rounding mode is Round to Nearest without any modification. Trying to change it seems to result in no difference w.r.t. the above test-case.

**Comment by penberg** [comment]
The problem is actually with Float.toString(float) and Double.toString(double), not with valueOf(). As it works just fine with JamVM, it's a bug in our JIT -> JNI transition (we're probably using wrong instructions to convert XMM registers to i386 ABI floating point arguments that are on stack).

**Comment by penberg** [comment]
Oh, it had nothing to do with JNI. We just needed to enable double-precision rounding mode.
